version: '3.9'

services:

  ## --------------------------------------------------
  ## | Database - MySQL latest
  ## --------------------------------------------------
  snapdr-db:
    image: mysql:latest
    container_name: snapdr-db
    volumes:
      - ./.docker/.data/database:/var/lib/mysql
    ports:
      - "${DB_HOST_PORT}:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env

  ## --------------------------------------------------
  ## | Queue - Rabbitmq
  ## --------------------------------------------------
  snapdr-rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - '${RABBITMQ_PORT}:5672'
      - '${RABBITMQ_WEB_PORT}:15672'
    env_file:
      - .env

  ## --------------------------------------------------
  ## | Web Server - php:8.1.0-apache
  ## --------------------------------------------------
  snapdr-publisher:
    build:
      context: .docker/publisher
      dockerfile: Dockerfile
      args:
        - DATA_USER_ID=${DATA_USER_ID}
    container_name: snapdr-snapdr-publisher
    volumes:
      - ./snapdr-publisher/:/var/www/
      - ./.docker/snapdr-publisher/config/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "${BACKEND_PORT}:8105"
    restart: always
    environment:
      - DATA_USER_ID=${DATA_USER_ID}
      - EXCLUDE_PORTS=443
    depends_on:
      - snapdr-db
      - snapdr-rabbitm
    env_file:
      - .env

  ## --------------------------------------------------
  ## | Queue listener - php:8.1.0-cli
  ## --------------------------------------------------
  snapdr-consumer:
    build:
      context: .docker/consumer
      dockerfile: Dockerfile
      args:
        - DATA_USER_ID=${DATA_USER_ID}
    container_name: snapdr-snapdr-consumer
    volumes:
      - ./snapdr-consumer/:/var/www/
      - ./.docker/.data/consumer/log:/var/log/supervisor/
    restart: always
    environment:
      - DATA_USER_ID=${DATA_USER_ID}
    depends_on:
      - snapdr-publisher
    env_file:
      - .env
